### DISCUSSION TITLE
mitmproxy Docker certicate files not being initialized in /home/mitmproxy/.mitmproxy/

### DISCUSSION THREAD

**Discussion by dryu99** [mitmproxy/mitmproxy#5516] [Q&A] [answered]
I'm extending the `mitmproxy/mitmproxy` Docker image like so: 

```Dockerfile
FROM mitmproxy/mitmproxy

COPY setup.sh /usr/local/bin/setup.sh
RUN chmod +x /usr/local/bin/setup.sh

WORKDIR /usr/src/app/

COPY . .
```

When I use `mitmdump` as the default Docker command the certificate files are initialized in `/home/mitmproxy/.mitmproxy/` as [expected](https://hub.docker.com/r/mitmproxy/mitmproxy/):
```yml
  proxy:
    image: mitmproxy-v2 # name of the extended image
    container_name: proxy
    privileged: true
    ports:
      - 8080:8080    
    command: mitmdump --scripts /usr/src/app/mitm.py
```

However when I execute `setup.sh` as the default Docker command the certificate files aren't initialized: 

```sh
# setup.sh

#!/bin/bash
mitmdump --scripts /usr/src/app/mitm.py
```

Does anyone have any idea what's going on? I feel this might not have to do with `mitmproxy` but more with how Docker or bash works but I wanted to ask here just in case. Thanks for any help in advance!
