### DISCUSSION TITLE
Something wrong with config.yaml

### DISCUSSION THREAD

**Discussion by Sim4n6** [mitmproxy/mitmproxy#5994] [Q&A] [answered]
Hi, I don't know what is wrong with my CLI & code, please.

```yaml
eventlog: true
console_eventlog_verbosity: warn
set:
  passthrough_events: all

addons:
  - module: MODULE
    path: ./modules/module.py
  - module: upstream
    args: ["http://127.0.0.1:8089"]
    kwargs:
      ssl_insecure: true
      add_upstream_certs_to_client_chain: true
      block_global: false
    hosts:
      - www.a.com
      - www.b1.com
```

1. I placed the `config.yaml` into `~/.mitmproxy/` and tried `./mitmweb` did not work.
2. I placed the `config.yaml` in the same directory as mitmweb and tried `./mitmweb` did not work.
3. I renamed the `config.yaml` to `config.yml` nothing
4. I used `./mitmweb --conf configfile=~/.mitmproxy/config.yaml` did not work

I am using:

```
Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.0-67-generic-x86_64-with-glibc2.35
```
