### DISCUSSION TITLE
How to install additional packages on a dockerized mitmproxy?

### DISCUSSION THREAD

**Discussion by siktec-lab** [mitmproxy/mitmproxy#6186] [Q&A]
It should be pretty straightforward, yet I can't find a clean way to install packages to my mitmproxy container.

I'm building and running the container with docker-compose:

```
my-proxy:
        image: mitmproxy/mitmproxy
        container_name: my-proxy
        ports: 
          - 8080:8080
          - 8081:8081
        volumes:
          - ./certs:/home/mitmproxy/.mitmproxy
          - ./proxy_addon:/home/proxy_addon
        environment:
          - WCB_SILENT=False
        depends_on: 
          - wcb-cache
        restart: always
        command: pip install redis requests && mitmweb --web-host 0.0.0.0 --web-port 8081 -s /home/proxy_addon/addon_one.py
```

without `pip install redis requests` everything is working fine but when I ran it with - I get warnings and notices:

```
wcb-proxy        | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
wcb-proxy        |
wcb-proxy        | [notice] A new release of pip available: 22.3 -> 23.1.2
wcb-proxy        | [notice] To update, run: pip install --upgrade pip
wcb-proxy exited with code 0
wcb-proxy        | Requirement already satisfied: redis in /usr/local/lib/python3.11/site-packages (4.5.5)
wcb-proxy        | Requirement already satisfied: requests in /usr/local/lib/python3.11/site-packages (2.31.0)
wcb-proxy        | Requirement already satisfied: async-timeout>=4.0.2 in /usr/local/lib/python3.11/site-packages (from redis) (4.0.2)
wcb-proxy        | Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests) (3.1.0)
wcb-proxy        | Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests) (3.4)
wcb-proxy        | Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests) (2.0.3)
wcb-proxy        | Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests) (2022.9.24)
```

And it keeps restarting.

I want it to be installed automatically without connecting to the container and manually installing additional packages.

What is the correct way to add more Python packages when using the mitmproxy docker image?
