### DISCUSSION TITLE
mitmweb - connection lost with nginx reverse proxy

### DISCUSSION THREAD

**Discussion by phucnb** [mitmproxy/mitmproxy#6960] [Q&A] [answered]
I have a docker-compose:

```
version: '3'
services:
  mitmweb:
    image: mitmproxy/mitmproxy
    tty: true
    networks:
      - mitmproxy_net
    ports:
      - "127.0.0.1:8081:8081"
      - "51820:51820/udp"
    volumes:
      - /home/test/mitmproxy/mitmproxy_volume:/home/mitmproxy/.mitmproxy
    command: /bin/bash -c "pip install requests && mitmweb --mode wireguard --set ssl_insecure=true --set block_global=false --set confdir=/home/mitmproxy/.mitmproxy/confdir -s /home/mitmproxy/.mitmproxy/scripts/script.py --web-host 0.0.0.0 "

networks:
  mitmproxy_net:
    driver: bridge
```

I have a nginx reverse proxy set up:
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /mitm/ {
        proxy_pass http://127.0.0.1:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }

}

```

When I open the URL public_ip/mitm, I can see the UI but the QR code not showing as well as no traffics, it show **connection lost** and from the container logs, i can see the **/updates** return 400 and some js return 404.
![Screenshot 2024-06-25 at 5 49 29 PM](https://github.com/mitmproxy/mitmproxy/assets/7269838/bcd0ab9c-b907-4627-8c02-1d09d213d74c)
<img width="1004" alt="Screenshot 2024-06-25 at 5 49 56 PM" src="https://github.com/mitmproxy/mitmproxy/assets/7269838/906d1c7c-09ed-4169-ac10-30e5d8197585">

If I change the port mapping in docker-compose from : **"127.0.0.1:8081:8081"** to **"8081:8081"** then I can access to public_ip:8081 and everything works perfectly, I can see the traffics from WireGuard clients **but access to the URL public_ip/mitm still the same result above**.
 
My goal is only able to access to the web through URL but port.
