### ISSUE TITLE
mitmweb isn't protected against DNS rebinding

### ISSUE THREAD

**Issue by atx** [mitmproxy/mitmproxy#3234]
The mitmweb interface does not seem to include protection against DNS rebinding. This could be exploited by a malicious website to either access the sniffed data or run arbitrary Python scripts on the filesystem by setting the `scripts` config option. 

I have hacked together a PoC [here](http://arya.atx.name/mmp.html) (nothing really special to be seen though).

**Comment by mhils** [comment]
Thanks for raising this. Any recommendations on how we can fix this best?

**Comment by atx** [comment]
I like the Jupyter implementation - effectively password protect the web interface, but pass an access token to your `webbrowser.open` call not to annoy the user too much. As a simpler alternative, you can implement Host header based whitelist (allowing localhost or IP address access by default).

**Comment by mhils** [comment]
Thanks again - we've just released mitmproxy 4.0.4, which includes the fix from #3243. :)

**Comment by ILoveStreaming3** [comment]
Can I allow binding? Trying to use ngrok

**Comment by chrisooo3** [comment]
Is it possible to turn it off and allow DNS rebinding?

**Comment by stellarpower** [comment]
Would also like to know if this can be disabled - my instance is behind a reverse proxy so I am presuming this is safe enough for what I need it for, and accessing it externally would be helpful.

**Comment by ananthb** [comment]
Yes would love for this to be configurable.

**Comment by DenisBalan** [comment]
As @Kriechi merged https://github.com/mitmproxy/mitmproxy/pull/3243 into the master.
Also mentioning @mhils @atx 

Whats the problem having by default DnsBinding protection enabled,
but have this option configurable?

In our case, for internal usage purposes, we need to fork this repo and revert mentioned PR in order to fulfill our needs.

IMHO, thats not the best way to do that.
Just make secure by default, and configurable for those who `knows what they are doing`

**Comment by chrisbecke** [comment]
What the actual ...... ..... A day spent trying to figure out why a docker swarm Traefik router for `mitmweb.example.com` always returned 404.

**Comment by hoogi91** [comment]
@chrisbecke regarding traefik you need to disable passHostHeader see below example using compose - hope it helps you too :)
```
mitmproxy:
    image: mitmproxy/mitmproxy
    tty: true
    command: "mitmweb --web-host *"
    labels:
      - "traefik.http.services.mitmproxy.loadbalancer.server.port=8081"
      - "traefik.http.services.mitmproxy.loadbalancer.passHostHeader=false"
```

**Comment by chrisbecke** [comment]
Ive passed that, and used a middleware to set the host header to 1.1.1.1 - but the websocket that fetches updates always says "connection lost", or "connecting" forever.

**Comment by hoogi91** [comment]
@chrisbecke ah sry, forgot to mention them too, you also need to add a middleware that drops some request headers to make the websocket work:
```
      - "traefik.http.routers.mitmproxy-https.middlewares=mitmproxy-header@docker"
      - "traefik.http.middlewares.mitmproxy-header.headers.isDevelopment=true"
      - "traefik.http.middlewares.mitmproxy-header.headers.customrequestheaders.Host="
      - "traefik.http.middlewares.mitmproxy-header.headers.customrequestheaders.Origin="
```

**Comment by dhananjayraut** [comment]
I was able to get it working with nginx (NPM actually) as reverse proxy by adding following two lines in config and allowing websocket
```
   proxy_set_header Host "";
   proxy_set_header Origin "";
```

**Comment by SciLor** [comment]
How to implement this workaround for nginx-proxy-manager?

**Comment by wu0407** [comment]
It is work for kubernetes traefik ingressRoute:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik2
  name: mitmproxy
  namespace: xxxx
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`web.xxxx.com`)
    services:
    - kind: Service
      name: mitmproxy
      namespace: weimob-ops
      port: 8081
    middlewares:
    - name: mitmproxy-web-header
      namespace: xxx
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mitmproxy-web-header
  namespace: xxx
spec:
  headers:
    customRequestHeaders:
      # hack to remove origin request Host header
      # may be relate https://github.com/traefik/traefik/pull/6502
      Host: " " # this is a space 
      Origin: ""
    isDevelopment: true
```

**Comment by davet2001** [comment]
Here's what I eventually got working on haproxy for a home assistant docker container.
```
frontend main
    bind *:8081

    http-response del-header    x-frame-options
    default_backend             mitmweb

backend mitmweb
    balance     roundrobin
    http-request set-header Host 127.0.0.1:9090
    http-request set-header Origin http://127.0.0.1:9090
    server  mitm    127.0.0.1:9090 check
```
In my case, haproxy is listening on `8081`, then proxying this to a mitmproxy instance running its web server on `9090`.  Both of these are inside a docker container.

The `http://` on the origin header line turned out to be important. I'm not fully sure why, but without this, the websocket connection was not allowed through haproxy to mitmproxy.

**Comment by jasonholloway** [comment]
A further potentially helpful snippet for users of Kubernetes' Nginx controller:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "127.0.0.1:8081"
```

**Comment by ryansorensen** [comment]
For anyone using Caddy as their reverse proxy:

```
https://mitmproxy.example.com {
	reverse_proxy * localhost:8081 {
		header_up Host 127.0.0.1:8081
		header_up Origin http://127.0.0.1:8081
	}
}
```

example docker-compose.yml

```
services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    command: mitmweb --web-host 0.0.0.0
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - /mitmproxy-data:/home/mitmproxy/.mitmproxy
```
