### ISSUE TITLE
Windows Docker container mitmweb.exe web port issue

### ISSUE THREAD

**Issue by jaybauson** [mitmproxy/mitmproxy#4249]
#### Problem Description
I have Windows containers and the reason why I decided to create a dockerized mitmproxy. The problem is that I am able to map the listen port, but for some reason, the web port is only accessible inside the container. Here's the Dockerfile and YAML file for those who want to try it. I know there's no official Windows image for mitmproxy, but maybe we can start it with this because it could happen. Anyone had nay success to dockerized mitmproxy?

**Dockerfile**
````Dockerfile
FROM microsoft/windowsservercore:ltsc2016
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
WORKDIR C:\\mitm
RUN $url = ('https://snapshots.mitmproxy.org/5.2/mitmproxy-5.2-windows.zip'); \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Uri $url -OutFile mitm.zip; \
	Expand-Archive -Path 'C:\mitm\mitm.zip' -DestinationPath 'C:\mitm' -Force; \
	Write-Host 'Removing ...'; \
	Remove-Item 'C:\mitm\mitm.zip' -Force; 
	
	
RUN $url = ('https://www.python.org/ftp/python/3.9.0/python-3.9.0-amd64.exe'); \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Uri $url -OutFile python-3.9.0-amd64.exe; \
	Start-Process C:\mitm\python-3.9.0-amd64.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ; \
	Write-Host 'Removing ...'; \
	Remove-Item 'C:\mitm\python-3.9.0-amd64.exe' -Force; 	
	
	
RUN $url = ('https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe'); \
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
	Invoke-WebRequest -Uri $url -OutFile vc_redist.x64.exe; \
	Start-Process 'C:\mitm\vc_redist.x64.exe' -ArgumentList '/install /quiet /norestart' -Wait ; \
	Write-Host 'Removing ...'; \
	Remove-Item 'C:\mitm\vc_redist.x64.exe' -Force; 		


CMD [ "ping", "localhost", "-t" ] ## Update this part
### .\\mitmweb.exe --no-web-open-browser --listen-port 40001 --mode reverse:http://10.186.199.217:7001/
````
**YAML**
````YAML
# mitm.yml
version: '3.7'

services:
  mitm1:
    image: mitmproxy-win
    working_dir: 'C:\mitm\'
    command: '.\\mitmweb.exe --no-web-open-browser --listen-port 40001 --mode reverse:http://10.186.199.217:7001/'
    ports:
      - target: 40001
        published: 40001
        protocol: tcp
        mode: host
      - target: 8081
        published: 40011
        protocol: tcp
        mode: host
    networks:
      - sbe


networks:
  sbe:
    external: true 
````
#### Steps to reproduce the behavior:
1. docker build -t mitmproxy-win .
2. docker stack deploy -c mitm.yml mitm
3. Inside the container, I can do `Invoke-WebRequest -Uri http://localhost:8081 -UseBasicParsing` without a problem
4. But in the host, `Invoke-WebRequest -Uri http://localhost:40011/  -UseBasicParsing` is failing with the following error:
````powershell
Invoke-WebRequest : Unable to connect to the remote server
At line:1 char:1
+ Invoke-WebRequest -Uri http://localhost:40011 -UseBasicParsing
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
````
I already tried to change the web port but just got the same behavior. 

#### System Information
Paste the output of "mitmweb.exe --version" here.
Mitmproxy: 5.2 binary
Python:    3.7.8
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Windows-10-10.0.14393-SP0
