### ISSUE TITLE
Provide an easy way to set target (domain) specific options

### ISSUE THREAD

**Issue by buyabez** [mitmproxy/mitmproxy#4388]
#### Problem Description

mitproxy does not provide an easy way to set target specific options.

Example:
For "target A" I need to exclude a set of domains from the flow list and use a custom "script A" that injects a header into each request send to "target A". 
Then again I have a "target B" that uses different domains and different script(s) and additional options required only for "target B".

#### Proposal
A new mitmproxy command line option (e.g. '-f') to specify a configuration (yaml) that is being used to set the different options.
Using a default name for such an configuration file, would allow the user's of mitmproxy to just provide  a file like 'mitmproxy.yml' in the current directory 
e.g.

/home/me/targets/target.a.com/mitmproxy.yaml
/home/me/targets/target.b.com/mitmproxy.yaml

#### Alternatives
So far this can be achieved by using custom starter scripts (e.g. bash) to provide different the different command line args to mitproxy, which requires to create scripts for each target

Target A
```
#!/bin/bash
mitmproxy -w flow.txt --view-filter '~d "(.target.a.net)" & !(~t image*)' -s inject-request-header.py $@
```

Target B
```
#!/bin/bash
mitmproxy -w flow.txt --view-filter '~d "(.target.b.net)" & !(~t image*)' -s inject-response-header.py $@
```

Another solution (as suggested in the Slack channel #general) is to use the command line option  ```mitmproxy --set confdir=...```
to change your default configuration directory from ~/.mitmproxy to something else. 
This solution is a bit unhandy since mitmproxy will create a new set of CA certs for the new confdir that one has to import into the browsers trusted list of CAs

#### Additional context
Example configuration structure in YAML just for illustration purpose
```
target:
  flows:
    include:
      - target.a.com
      - target.a.eu
      - data.target.a.com
      - api.target.a.com
    exclude: 
      - .target.a.net
      - partner.target.a.com
      - type:image/*
    scripts:
      - inject-request-header.py
```
