### ISSUE TITLE
Custom onboarding_host returns Bad Gateway

### ISSUE THREAD

**Issue by hazcod** [mitmproxy/mitmproxy#4500]
#### Problem Description
Defining a custom onboarding_host returns 'Bad Gateway'.
FYI this works with `mitm.it` and `80`.

#### Steps to reproduce the behavior:
1. In config.yaml:
```yaml
onboarding_port: 443
onboarding_host: 'proxy.company.com'
``` 
2. Run container: `docker run -ti --rm -p 127.0.0.1:443:8080 mitmproxy`
3. Test:
```shell
% curl --resolve 'proxy.company.com:443:127.0.0.1' -k https://proxy.company.com/
<html>
<head>
    <title>502 Bad Gateway</title>
</head>
<body>
    <h1>502 Bad Gateway</h1>
    <p>[Errno -2] Name or service not known</p>
</body>
</html>%
```

#### System Information
```
Mitmproxy: 7.0.0.dev
Python:    3.9.2
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-4.19.121-linuxkit-aarch64-with-glibc2.31
```

**Comment by mhils** [comment]
I can't replicate this locally, the following works fine for me:

```
mitmdump --set onboarding_host=proxy.company.com --set onboarding_port=443 -p 443
curl --resolve 'proxy.company.com:443:127.0.0.1' -k https://proxy.company.com/
```

Is this a docker issue with inside port != outside port?

**Comment by mhils** [comment]
FWIW your config is a bit off here: Your mitmproxy instance is running as a regular HTTPS proxy, so you should do `curl -x proxy:port -k https://proxy.company.com`, which also works fine.

**Comment by hazcod** [comment]
Hmm, interesting.

```yaml
onboarding_port: 443
onboarding_host: 'proxy.company.com'
```

```shell
% curl -x localhost:443 -k https://proxy.company.com/
<html>
<head>
    <title>502 Bad Gateway</title>
</head>
<body>
    <h1>502 Bad Gateway</h1>
    <p>[Errno -2] Name or service not known</p>
</body>
</html>%  
```

**Comment by mhils** [comment]
```
mitmdump --set onboarding_host=proxy.company.com --set onboarding_port=443
curl -x localhost:8080 -k https://proxy.company.com
```

works fine for me.

**Comment by hazcod** [comment]
Hmm, having problems running mitmproxy on my system itself.
For ref, config:
```yaml

# don't buffer responses to improve performance and memory usage
# we don't want to log those anyway
stream_large_bodies: "1k"

# but don't do this for websocket since this is typically small
# and we can't modify when streaming
stream_websockets: false

# allow requests from the internet since we do authn
block_global: false
block_private: false

# set log level to info
console_eventlog_verbosity: warn

# no need
flow_detail: 0
console_mouse: false
command_history: false
onboarding: false
relax_http_form_validation: true

# our custom scripts
scripts: ["plugins/intigriti.py"]

# we support http2, but don't prioritize it
http2: true
http2_priority: false

# surf to this address to download certificate
onboarding_port: 443
onboarding_host: 'proxy.company.com'

# experimental support for raw tcp
rawtcp: true

# ca settings
key_size: 2048

# we serve stuff
server: true
websocket: true
listen_host: '0.0.0.0'
listen_port: 8080

# if customers don't configure their server right..
ssl_insecure: true
```
