### ISSUE TITLE
Specify how to run Dockerized mitmweb in docker-compose

### ISSUE THREAD

**Issue by ctsrc** [mitmproxy/mitmproxy#4996]
#### Problem Description

When attempting to run mitmweb via docker-compose, I found that I was not able to access the mitmweb UI even though it had been working when running without using Docker and it had been working when running with Docker directly.

#### Proposal

The README should specify how to ensure that the Web UI is accessible when running via docker-compose.

The solution is that inside of Docker, mitmweb Web UI must listen on 0.0.0.0:8081 instead of on 127.0.0.1:8081

This is achieved by making use of the `--listen-host` argument of `mitmweb`.

Here is a pretty minimal `docker-compose.yml` file that includes mitmweb with web UI that can be connected to from the host:

```yml
version: "3"

services:
  hello_world:
    image: digitalocean/flask-helloworld
    container_name: hello_world
  mitmproxy:
    image: mitmproxy/mitmproxy:latest
    container_name: hello_mitmproxy
    command: mitmweb --web-host 0.0.0.0 --mode reverse:http://hello_world:5000/
    ports:
      - 8080:8080
      - 127.0.0.1:8081:8081
```

Then you have the proxied service available at http://0.0.0.0:8080 and the mitmweb Web UI available on http://127.0.0.1:8081

Adapt as needed in terms of services running in the docker compose network.

The key point is the inclusion of `--web-host 0.0.0.0` in the command of the mitmproxy service.
