### ISSUE TITLE
ignore_hosts and allow_hosts should be additive, not exclusive. 

### ISSUE THREAD

**Issue by otheus** [mitmproxy/mitmproxy#5270]
#### Problem Description

Specify hosts which to "whitelist" as exceptions to a "blacklist" and vice-versa. 

#### Proposal
Change the options so that _allow_hosts_ and  _ignore_hosts_ are not mutually exclusive, but additive. As with old Apache httpd configs, there should be a switch indicating whether the order is ignore-allow, or allow-ignore. 

Use-case:

We want to monitor only those requests to a particular domain except those hosts which incorporate pinning. All others, including the pinned, get passed through. We'd need a config like:

```yaml
  allow_hosts:  [ \bourdomain\.com, \bourdomain2\.com ]
  ignore_hosts:  [ '^accounts\.ourdomain\.com, login\.ourdomain2\.com ]
  allow_ignore_precedence: "ignore"
```

In the above example, `ignore_hosts` are checked first. In the following scenario, we want `allow_hosts` to be evaluated first:

```yaml
  allow_hosts: [  store.cdn_provider.org  ]
  ignore_hosts:  [ '^store\.(.*)\.(org|com|net)$', '\b.cdn_provider.(org|com|net)$' ]
  allow_ignore_precedence: "allow"
```

* If "ignore" is specified, but not "allow", then the default is "allow all". 
* If "allow" is specified, but not "ignore", then the default is "ignore all".
* If both are specified the default is the value of "allow_ignore_precedence" . 

#### Alternatives

Alternative: Merge both into an ordered, firewall like list:

```yaml
  filter_default:  <allow | ignore>
  filter_hosts:
    - allow: <regex>
    - ignore: <regex>
    - allow: <regex>
    - allow: <regex>
    - ignore: <regex>
```
