### ISSUE TITLE
Is Web Password a must??

### ISSUE THREAD

**Issue by borisspektor** [mitmproxy/mitmproxy#7551]
### Problem Description

I am using mitmweb without a password and now I don't see a way to do so.
How can I run mitmweb without requiring a password from the user?

### System Information

```raw

```

### Checklist

- [x] This bug affects the [latest mitmproxy release](https://github.com/mitmproxy/mitmproxy/releases).

**Comment by peterpeppered** [comment]
to add : we just updated the mitmproxy docker image to 11.1.2 and suddenly got this :

![Image](https://github.com/user-attachments/assets/861e4ab7-8fd8-4a93-98d6-07d9523e1d81)

but copy/pasting the token from the container log just sends us into a loop, the token is never accepted...

**Comment by mhils** [comment]
refs https://github.com/mitmproxy/mitmproxy/discussions/7544, but let's continue here.

Two questions for you folks:

1. What's your use case? Why does the default token generation or setting a fixed password not work for you? Access the the web UI is pretty much RCE, so I'm hesitant to provide an option that disables authentication.
2. @peterpeppered: Could you please share repro steps? What do you see in your browser logs, what do you see in your mitmproxy logs?

**Comment by peterpeppered** [comment]
usecase is using the default mitmproxy container in a local dev stack with multiple other containers (for local development). current compose :
```
    mitmproxy:
        image: mitmproxy/mitmproxy
        container_name: mitmproxy
        volumes:
            - ./docker/mitmproxy:/home/mitmproxy/.mitmproxy
        ports:
            - "8081:8081"
            - "8080"
        command: mitmweb --web-host 0.0.0.0
        networks:
            - traefik
```
after this is started, the webinterface shows me the dialog to paste a token, but the `docker logs <container-id>` shows things like :
```
[12:08:15.313] HTTP(S) proxy listening at *:8080. [12:08:15.315] Web server listening at http://0.0.0.0:8081/?token=759070597a73fcb7d1470f25b1f9f39f [12:08:15.350] No web browser found. Please open a browser and point it to http://0.0.0.0:8081/?token=759070597a73fcb7d1470f25b1f9f39f
```
but... come to think of it, this output seems to only appear after stopping the container, so I guess the token I'm seeing is from the previous run, and hence invalid ? hmmm

...

just tried again, and it seems I'm indeed seeing old logs. I have no idea how to get a current token then.
